version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "team"
    allow:
      - dependency-type: "direct"
